
---
- hosts: alician-media
  tasks:
    - name: Install packages
      become: true
      apt:
        name:
          - vim
          - openssh-server
          - make
          - python-pip
          - ubuntu-restricted-extras
          - zfsutils-linux

    - name: Check if Caps is mapped to Control
      shell: setxkbmap -query | grep ctrl:nocaps
      changed_when: caps_to_control.rc == 1
      failed_when: caps_to_control.rc > 1
      register: caps_to_control

    - name: Remap Caps to Control
      shell: setxkbmap -option ctrl:nocaps && gsettings set org.gnome.settings-daemon.plugins.keyboard active false
      when: caps_to_control.rc == 1
      ignore_errors: yes

    - name: Get Tom's SSH keys from Github
      uri:
        url: https://github.com/tdooner.keys
        return_content: true
      register: github_keys

    - name: Set up SSH keys for {{ ansible_user }}
      authorized_key:
        user: '{{ ansible_user }}'
        key: '{{ github_keys.content }}'

    - name: Configure SSH to forbid password authentication
      become: true
      register: updated_ssh_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^(#)?PasswordAuthentication (yes|no)'
        line: 'PasswordAuthentication no'
        validate: '/usr/sbin/sshd -f %s -t'

    - name: Restart ssh server
      become: true
      service:
        name: ssh
        state: restarted
      when: updated_ssh_config is success

    - name: Create media group to own the files
      become: true
      group:
        name: '{{ media_group }}'
        state: present

    - name: Add tdooner and tom to "media" group
      become: true
      user:
        name: '{{ item }}'
        groups: media
        append: true
        shell: /bin/bash
      with_items:
        - '{{ ansible_user }}'
        - '{{ media_user }}'

    - name: Remove download folders after two weeks
      become: true
      cron:
        name: "Remove download folders after two weeks"
        minute: 0
        hour: 0
        job: "find ~/Downloads/ -maxdepth 2 -mindepth 2 -type d -mtime +14 -exec rm -rf {} \\;"
        user: '{{ media_user }}'
