---
- hosts: alician-media
  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
      listen: reload systemd

  tasks:
    - name: Install deluge
      become: true
      apt:
        name: '{{ item }}'
      with_items:
        - deluged
        - deluge-web
        - deluge-console

    - name: Install deluge and deluge-web systemd services
      become: true
      copy:
        src: 'files/{{ item }}.service'
        dest: '/etc/systemd/system/{{ item }}.service'
      notify:
        - reload systemd
      with_items:
        - deluge
        - deluge-web

    - name: Start deluge services
      become: true
      systemd:
        name: '{{ item }}'
        enabled: true
        state: started
      with_items:
        - deluge
        - deluge-web
