---
- hosts: alician-media
  vars: {}
  tasks:
    - name: Install docker-py for ansible docker_container
      pip:
        # with Python > 2.6 this becomes "docker"
        name: docker-py

    - name: Create homeassistant user
      become: true
      user:
        name: homeassistant

    - name: Create homeassistant directory
      become: true
      file:
        path: /opt/home-assistant/config
        state: directory
        owner: homeassistant
        group: media
        mode: 0775

    - name: Generate homeassistant config
      template:
        src: templates/home-assistant.yml.j2
        dest: /opt/home-assistant/config/configuration.yaml

    # docker run -d \
    # --name homeassistant \
    # --privileged \
    # --restart=unless-stopped \
    # -e TZ=America/Los_Angeles \
    # -v /opt/home-assistant/config:/config \
    # -v /run/dbus:/run/dbus:ro \
    # --network=host \
    # ghcr.io/home-assistant/home-assistant:stable
 
    # TODO: This doesn't work, it gives a python error. Upgrade everything?
    # - name: Run docker container
    #   docker_container:
    #     name: homeassistant
    #     image: ghcr.io/home-assistant/home-assistant:stable
    #     privileged: yes
    #     restart: yes
    #     restart_policy: unless-stopped
    #     env:
    #       TZ: America/Los_Angeles
    #     volumes: # with Ansible 2.9 this becomes "mounts"
    #       - source: /run/dbus
    #         target: /run/dbus
    #         read_only: yes
    #     network_mode: host
