---
- hosts: alician-media
  tasks:
    - name: Install kodi apt package
      become: true
      apt:
        name: kodi

    - name: Add GUI user to dialout group for CEC thing
      become: true
      user:
        name: '{{ ansible_user }}'
        groups: dialout
        append: true
