---
- hosts: alician-media
  handlers:
    - name: reload nginx
      become: true
      service: name=nginx state=reloaded

  tasks:
    - name: Install certbot PPA
      become: true
      apt_repository:
        repo: ppa:certbot/certbot

    - name: Install packages
      become: true
      apt:
        name: '{{ item }}'
      with_items:
        - nginx
        - python-certbot-nginx

    - name: Install nginx configuration
      become: true
      template:
        src: templates/nginx-site.conf
        dest: /etc/nginx/sites-enabled/plex.tdooner.com
      notify:
        - reload nginx

    - name: Install nginx username/password config
      become: true
      template:
        src: templates/nginx-htpasswd.conf
        dest: /etc/nginx/htpasswd
