---
- hosts: alician-media
  vars:
    tautulli_version: 2.1.39

  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
      listen: reload systemd

  tasks:
    - name: Download and install Plex debian package
      become: true
      shell: 'wget -O /tmp/plex.deb https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=y1ejWrGTaEsBzmC3Cz7k && dpkg -i /tmp/plex.deb'
      args:
        creates: /lib/systemd/system/plexmediaserver.service

    - name: Add plex user to media group
      become: true
      user:
        name: plex
        groups: media
        append: true
