---
- hosts: alician-media
  vars:
    tautulli_version: 2.1.39

  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
      listen: reload systemd

  tasks:
    - name: Download and install Plex debian package
      become: true
      shell: 'wget -O /tmp/plex.deb https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token=y1ejWrGTaEsBzmC3Cz7k && dpkg -i /tmp/plex.deb'
      args:
        creates: /lib/systemd/system/plexmediaserver.service

    - name: Add plex user to media group
      become: true
      user:
        name: plex
        groups: media
        append: true

    - name: Make Tautulli directory
      become: true
      file:
        path: /opt/tautulli
        state: directory
        owner: plex
        group: media
        mode: 0775

    - name: Download Tautulli
      become: true
      unarchive:
        remote_src: yes
        src: "https://github.com/Tautulli/Tautulli/archive/v{{ tautulli_version }}.tar.gz"
        creates: /opt/tautulli/Tautulli-{{ tautulli_version }}
        dest: /opt/tautulli
        owner: plex
        group: media

    - name: Install Tautulli systemd service
      become: true
      template:
        src: templates/tautulli.service
        dest: /etc/systemd/system/tautulli.service
      notify:
        - reload systemd

    - name: Start Tautulli service
      become: true
      systemd:
        name: tautulli
        enabled: true
        state: started
