---
- hosts: alician-media
  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
      listen: reload systemd
    - name: restart radarr
      become: true
      command: systemctl restart radarr
      listen: restart radarr

  tasks:
  - getent:
      database: passwd
      key: "{{ media_user }}"
  - getent:
      database: group

  - name: Create Radarr directory
    become: true
    file:
      path: '{{ item }}'
      state: directory
      owner: '{{ media_user }}'
      group: '{{ media_group }}'
    with_items:
      - /opt/radarr
      - /opt/radarr/config

  - name: Install radarr systemd service
    become: true
    template:
      src: templates/radarr.service
      dest: /etc/systemd/system/radarr.service
    notify:
      - reload systemd
      - restart radarr

  - name: Start radarr service
    become: true
    systemd:
      name: radarr
      enabled: true
      state: started
