---
- hosts: alician-media
  vars:
    sabnzbd_version: 2.3.9

  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
      listen: reload systemd

  tasks:
  - name: Create SABnzbd directory
    become: true
    file:
      path: '{{ item }}'
      state: directory
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
    with_items:
      - /opt/sabnzbd

  - name: Download and extract SABnzbd
    unarchive:
      remote_src: true
      src: https://github.com/sabnzbd/sabnzbd/releases/download/{{ sabnzbd_version }}/SABnzbd-{{ sabnzbd_version }}-src.tar.gz
      dest: /opt/sabnzbd
      creates: /opt/sabnzbd/SABnzbd-{{ sabnzbd_version }}

  - name: Install Pip
    apt:
      name: python-pip

  - name: Install Virtualenv
    pip:
      name: virtualenv

  - name: Create SABnzbd virtualenv
    command: python -m virtualenv /opt/sabnzbd/env
    args:
      creates: /opt/sabnzbd/env

  - name: Install decompression utils
    become: true
    apt:
      name: '{{ item }}'
    with_items:
      - unrar
      - par2

  - name: Install SABnzbd python dependencies
    pip:
      name: '{{ item }}'
      virtualenv: /opt/sabnzbd/env
    with_items:
      - cheetah
      - yenc
      - sabyenc

  - name: Install sabnzbd systemd service
    become: true
    template:
      src: templates/sabnzbd.service
      dest: /etc/systemd/system/sabnzbd.service
    notify:
      - reload systemd

  - name: Start SABnzbd service
    become: true
    systemd:
      name: sabnzbd
      enabled: true
      state: started
