---
- hosts: alician-media
  handlers:
    - name: reload smbd
      become: true
      service: name=smbd state=restarted
    - name: reload avahi
      become: true
      service: name=avahi-daemon state=restarted
    - name: reload netatalk
      become: true
      service: name=netatalk state=restarted

  tasks:
    - name: Install samba/avahi/netattalk packages
      become: true
      apt:
        name: '{{ item }}'
      with_items:
        - samba
        - avahi-daemon
        - netatalk

    - name: Install samba configuration
      become: true
      template:
        src: templates/avahi-smb.conf
        dest: /etc/avahi/services/smb.conf
      notify:
        - reload avahi

    # instructions from: https://blog.alt255.com/post/timemachine/
    - name: Update nsswitch.conf
      become: true
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts: '
        line: 'hosts:          files mdns4_minimal [NOTFOUND=return] dns mdns4 mdns'

    - name: Install netatalk configuration
      become: true
      template:
        src: templates/netatalk-volumes.conf
        dest: /etc/netatalk/AppleVolumes.default
      notify:
        - reload avahi
        - reload netatalk

    - name: Allow Netatalk through firewall
      become: true
      ufw:
        rule: allow
        port: 458
        proto: tcp

    - name: Allow simple service discovery protocol
      become: true
      ufw:
        rule: allow
        port: 1900
        proto: udp

# TODO: Update config file
# TODO: Set samba local user password somehow
