---
- hosts: alician-media
  tasks:
    - name: Install transmission
      become: true
      apt:
        name: '{{ item }}'
      with_items:
        - transmission
        - transmission-daemon

# TODO: Add "192.168.*.*" to rpc whitelist
# TODO: Set download directory
