
---
- hosts: alician-media
  handlers:
    - name: reload systemd
      become: true
      command: systemctl daemon-reload
      listen: reload systemd
    - name: restart radarr
      become: true
      command: systemctl restart watchtower
      listen: restart watchtower

  tasks:
  - name: Install watchtowen systemd service
    become: true
    template:
      src: templates/watchtower.service
      dest: /etc/systemd/system/watchtower.service
    notify:
      - reload systemd
      - restart watchtower

  - name: Start watchtower service
    become: true
    systemd:
      name: watchtower
      enabled: true
      state: started
